import type { Specialist } from "../types";

export const cities: string[] = [
  "თბილისი",
  "ქუთაისი",
  "ბათუმი",
  "რუსთავი",
  "ზუგდიდი",
  "თელავი",
  "გორი",
  "ახალციხე",
];

export const subspecialties: string[] = [
  "პერინატოლოგია",
  "ულტრაბგერითი დიაგნოსტიკა",
  "სამედიცინო გენეტიკა",
  "ნეონატოლოგია",
  "სამეანო ანესთეზიოლოგია",
];

export const languages: string[] = ["ქართული", "ინგლისური", "რუსული", "სომხური", "აზერბაიჯანული"];

export const specialists: Specialist[] = [
  {
    id: "sp-01",
    name: "პროფ. ნინო ჩხარტიშვილი",
    title: "პერინატოლოგი, სამედიცინო დირექტორი",
    clinic: "დედათა და ბავშვთა ეროვნული ცენტრი",
    city: "თბილისი",
    region: "თბილისი",
    subspecialties: ["პერინატოლოგია", "ულტრაბგერითი დიაგნოსტიკა"],
    languages: ["ქართული", "ინგლისური", "რუსული"],
    phone: "+995 32 291 44 10",
    email: "n.chkhartishvili@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2004,
    bio: "სპეციალიზდება პრეეკლამფსიისა და ჰიპერტენზიული დარღვევების მართვაში. MFM საქართველოს პრეზიდენტი.",
  },
  {
    id: "sp-02",
    name: "პროფ. თამარ ბერიძე",
    title: "პერინატოლოგი, კვლევის ხელმძღვანელი",
    clinic: "თბილისის სამედიცინო უნივერსიტეტის კლინიკა",
    city: "თბილისი",
    region: "თბილისი",
    subspecialties: ["პერინატოლოგია"],
    languages: ["ქართული", "ინგლისური"],
    phone: "+995 32 254 08 77",
    email: "t.beridze@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2007,
    bio: "ნაადრევი მშობიარობის პრევენციის ეროვნული კვლევის მთავარი მკვლევარი.",
  },
  {
    id: "sp-03",
    name: "დრ. გიორგი მაისურაძე",
    title: "ულტრაბგერითი დიაგნოსტიკის სპეციალისტი",
    clinic: "პრენატალური დიაგნოსტიკის ცენტრი",
    city: "თბილისი",
    region: "თბილისი",
    subspecialties: ["ულტრაბგერითი დიაგნოსტიკა", "სამედიცინო გენეტიკა"],
    languages: ["ქართული", "ინგლისური", "რუსული"],
    phone: "+995 32 220 31 55",
    email: "g.maisuradze@example.ge",
    acceptsReferrals: true,
    telehealth: false,
    since: 2011,
    bio: "ნაყოფის ექოკარდიოგრაფიისა და სტრუქტურული ანომალიების დიაგნოსტიკის სპეციალისტი.",
  },
  {
    id: "sp-04",
    name: "დრ. ეკატერინე ლომიძე",
    title: "პერინატოლოგი",
    clinic: "ქუთაისის რეფერალური ჰოსპიტალი",
    city: "ქუთაისი",
    region: "იმერეთი",
    subspecialties: ["პერინატოლოგია"],
    languages: ["ქართული", "ინგლისური"],
    phone: "+995 431 24 55 09",
    email: "e.lomidze@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2013,
    bio: "იმერეთის რეგიონული პერინატალური ქსელის კოორდინატორი.",
  },
  {
    id: "sp-05",
    name: "დრ. ლევან ჯორბენაძე",
    title: "მეან-გინეკოლოგი, გადაუდებელი მდგომარეობები",
    clinic: "ბათუმის სამედიცინო ცენტრი",
    city: "ბათუმი",
    region: "აჭარა",
    subspecialties: ["პერინატოლოგია", "სამეანო ანესთეზიოლოგია"],
    languages: ["ქართული", "ინგლისური", "რუსული"],
    phone: "+995 422 27 61 30",
    email: "l.jorbenadze@example.ge",
    acceptsReferrals: true,
    telehealth: false,
    since: 2009,
    bio: "მასიური სისხლდენისა და დედის კრიტიკული მდგომარეობების მართვის ინსტრუქტორი.",
  },
  {
    id: "sp-06",
    name: "დრ. ანა კვარაცხელია",
    title: "ულტრაბგერითი დიაგნოსტიკის სპეციალისტი",
    clinic: "დედათა და ბავშვთა ეროვნული ცენტრი",
    city: "თბილისი",
    region: "თბილისი",
    subspecialties: ["ულტრაბგერითი დიაგნოსტიკა"],
    languages: ["ქართული", "ინგლისური"],
    phone: "+995 32 291 44 22",
    email: "a.kvaratskhelia@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2015,
    bio: "მრავალნაყოფიანი ორსულობისა და TTTS-ის დიაგნოსტიკის სპეციალისტი.",
  },
  {
    id: "sp-07",
    name: "დრ. მარიამ წიკლაური",
    title: "სამეანო ანესთეზიოლოგი",
    clinic: "თბილისის სამედიცინო უნივერსიტეტის კლინიკა",
    city: "თბილისი",
    region: "თბილისი",
    subspecialties: ["სამეანო ანესთეზიოლოგია"],
    languages: ["ქართული", "ინგლისური"],
    phone: "+995 32 254 08 91",
    email: "m.tsiklauri@example.ge",
    acceptsReferrals: false,
    telehealth: false,
    since: 2012,
    bio: "სამეანო ანესთეზიის უსაფრთხოებისა და მასიური ტრანსფუზიის პროტოკოლების სპეციალისტი.",
  },
  {
    id: "sp-08",
    name: "დრ. დავით ღლონტი",
    title: "ნეონატოლოგი",
    clinic: "ზუგდიდის რეგიონული ჰოსპიტალი",
    city: "ზუგდიდი",
    region: "სამეგრელო",
    subspecialties: ["ნეონატოლოგია"],
    languages: ["ქართული", "რუსული"],
    phone: "+995 415 22 40 18",
    email: "d.ghlonti@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2010,
    bio: "ნაადრევად დაბადებულ ახალშობილთა ინტენსიური თერაპიის სპეციალისტი.",
  },
  {
    id: "sp-09",
    name: "დრ. სოფიო გელაშვილი",
    title: "სამედიცინო გენეტიკოსი",
    clinic: "გენეტიკური კონსულტაციის ცენტრი",
    city: "თბილისი",
    region: "თბილისი",
    subspecialties: ["სამედიცინო გენეტიკა"],
    languages: ["ქართული", "ინგლისური", "რუსული"],
    phone: "+995 32 238 77 04",
    email: "s.gelashvili@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2014,
    bio: "პრენატალური გენეტიკური კონსულტირებისა და NIPT-ის ინტერპრეტაციის სპეციალისტი.",
  },
  {
    id: "sp-10",
    name: "დრ. ზურაბ კიკნაძე",
    title: "მეან-გინეკოლოგი",
    clinic: "რუსთავის ცენტრალური საავადმყოფო",
    city: "რუსთავი",
    region: "ქვემო ქართლი",
    subspecialties: ["პერინატოლოგია"],
    languages: ["ქართული", "აზერბაიჯანული", "რუსული"],
    phone: "+995 341 25 33 60",
    email: "z.kiknadze@example.ge",
    acceptsReferrals: true,
    telehealth: false,
    since: 2016,
    bio: "ქვემო ქართლის რეგიონული ქსელის წევრი; მუშაობს მრავალენოვან პაციენტებთან.",
  },
  {
    id: "sp-11",
    name: "დრ. ნათია ბოლქვაძე",
    title: "პერინატოლოგი",
    clinic: "ბათუმის სამედიცინო ცენტრი",
    city: "ბათუმი",
    region: "აჭარა",
    subspecialties: ["პერინატოლოგია", "ულტრაბგერითი დიაგნოსტიკა"],
    languages: ["ქართული", "ინგლისური", "თურქული"],
    phone: "+995 422 27 61 44",
    email: "n.bolkvadze@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2017,
    bio: "აჭარის რეგიონული პერინატალური ქსელის კოორდინატორი.",
  },
  {
    id: "sp-12",
    name: "დრ. ირაკლი ხუციშვილი",
    title: "მეან-გინეკოლოგი",
    clinic: "თელავის რაიონული საავადმყოფო",
    city: "თელავი",
    region: "კახეთი",
    subspecialties: ["პერინატოლოგია"],
    languages: ["ქართული", "რუსული"],
    phone: "+995 350 27 18 22",
    email: "i.khutsishvili@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2018,
    bio: "ტელემედიცინის პილოტ-პროექტის მონაწილე; კახეთის რეგიონის კოორდინატორი.",
  },
  {
    id: "sp-13",
    name: "დრ. ქეთევან შენგელია",
    title: "ნეონატოლოგი",
    clinic: "დედათა და ბავშვთა ეროვნული ცენტრი",
    city: "თბილისი",
    region: "თბილისი",
    subspecialties: ["ნეონატოლოგია"],
    languages: ["ქართული", "ინგლისური"],
    phone: "+995 32 291 44 38",
    email: "k.shengelia@example.ge",
    acceptsReferrals: true,
    telehealth: false,
    since: 2011,
    bio: "ნეონატალური ტრანსპორტირებისა და სტაბილიზაციის პროტოკოლების ავტორი.",
  },
  {
    id: "sp-14",
    name: "დრ. გვანცა ტაბატაძე",
    title: "მეან-გინეკოლოგი",
    clinic: "გორის რეფერალური ცენტრი",
    city: "გორი",
    region: "შიდა ქართლი",
    subspecialties: ["პერინატოლოგია"],
    languages: ["ქართული", "ინგლისური"],
    phone: "+995 370 27 09 15",
    email: "g.tabatadze@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2019,
    bio: "შიდა ქართლის რეგიონული ქსელის წევრი; გესტაციური დიაბეტის მართვის ტრენერი.",
  },
  {
    id: "sp-15",
    name: "დრ. ალექსანდრე მელიქიშვილი",
    title: "პერინატოლოგი",
    clinic: "ახალციხის რეგიონული ჰოსპიტალი",
    city: "ახალციხე",
    region: "სამცხე-ჯავახეთი",
    subspecialties: ["პერინატოლოგია", "ულტრაბგერითი დიაგნოსტიკა"],
    languages: ["ქართული", "სომხური", "რუსული"],
    phone: "+995 365 22 14 07",
    email: "a.melikishvili@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2015,
    bio: "სამცხე-ჯავახეთის რეგიონული ქსელის კოორდინატორი; მუშაობს სომხურენოვან პაციენტებთან.",
  },
];
