import type { MfmEvent } from "../types";
import { IMG } from "../images";

export const eventTypes: string[] = [
  "Congress",
  "Webinar",
  "Workshop",
  "Course",
  "General assembly",
];

export const events: MfmEvent[] = [
  {
    slug: "pirveli-wlis-skriningi-workshop",
    title: "First-trimester screening workshop",
    type: "Workshop",
    start: "2026-10-15",
    timeLabel: "10:00 – 15:00",
    location: "MFM Training Centre, 76 Vazha-Pshavela Ave",
    city: "Tbilisi",
    online: false,
    price: "Free for members · 80 GEL",
    cme: "5 CME credits",
    seats: 40,
    registrationOpen: true,
    excerpt:
      "A hands-on session on combined first-trimester screening — cervical length, NT, biochemical markers and risk calculation.",
    image: IMG.eventWorkshop,
    agenda: [
      { time: "10:00", title: "Registration and coffee" },
      {
        time: "10:30",
        title: "First-trimester screening: review of the evidence",
        speaker: "Prof. Nino Chkhartishvili",
      },
      {
        time: "11:45",
        title: "NT measurement technique and quality control",
        speaker: "Dr Giorgi Maisuradze",
      },
      { time: "13:00", title: "Lunch" },
      { time: "14:00", title: "Practical session on the machines", speaker: "Instructor team" },
    ],
    speakers: ["Prof. Nino Chkhartishvili", "Dr Giorgi Maisuradze", "Dr Ana Kvaratskhelia"],
    body: [
      "The workshop is aimed at obstetrician-gynaecologists and ultrasound specialists who perform first-trimester screening in their own practice.",
      "Group size is limited to 40 participants so that everyone has enough hands-on time at a machine.",
    ],
  },
  {
    slug: "hipertenzia-orsulobisas-vebinari",
    title: "Hypertension in pregnancy: management in outpatient practice",
    type: "Webinar",
    start: "2026-09-22",
    timeLabel: "19:00 – 20:30",
    location: "Online (Zoom)",
    city: "Online",
    online: true,
    price: "Free",
    cme: "1.5 CME credits",
    registrationOpen: true,
    excerpt:
      "A practical walk-through of the updated guideline: who to treat, when to start and how to titrate antihypertensive therapy.",
    image: IMG.eventWebinar,
    agenda: [
      { time: "19:00", title: "Introduction and guideline overview", speaker: "Dr Ekaterine Lomidze" },
      { time: "19:30", title: "Case discussion" },
      { time: "20:05", title: "Q&A" },
    ],
    speakers: ["Dr Ekaterine Lomidze", "Prof. Tamar Beridze"],
    body: [
      "The webinar is aimed at clinicians working in outpatient care, focusing on the decisions actually made at first contact.",
      "A recording will be available to MFM members on the learning platform within 48 hours.",
    ],
  },
  {
    slug: "mfm-globaluri-kongresi-2026",
    title: "MFM Global Congress 2026",
    type: "Congress",
    start: "2026-12-05",
    end: "2026-12-07",
    timeLabel: "09:00 – 18:00",
    location: "Tbilisi Congress Centre",
    city: "Tbilisi",
    online: false,
    price: "Early bird — 240 GEL · Standard — 380 GEL",
    cme: "18 CME credits",
    seats: 600,
    registrationOpen: true,
    excerpt:
      "The year's main forum in maternal-fetal medicine: 40+ speakers, 5 plenary sessions, 12 parallel workshops.",
    image: IMG.eventCongress,
    agenda: [
      { time: "Day 1", title: "Plenary: the future of high-risk pregnancy care" },
      { time: "Day 1", title: "Parallel sessions: pre-eclampsia, diabetes, preterm birth" },
      { time: "Day 2", title: "Original research presentations" },
      { time: "Day 2", title: "Simulation workshops" },
      { time: "Day 3", title: "Patient-centred care and ethics" },
    ],
    speakers: [
      "Prof. Nino Chkhartishvili",
      "Prof. Tamar Beridze",
      "Dr Levan Jorbenadze",
      "International invited speakers",
    ],
    body: [
      "The congress is held every two years and brings together perinatologists, obstetrician-gynaecologists, neonatologists, midwives and researchers.",
      "## Abstract submission",
      "The deadline for abstracts is 15 September. Original research, case series and quality improvement projects are all accepted.",
      "## Travel grants",
      "Thirty travel grants covering registration and accommodation are available for participants from regional centres and for residents.",
    ],
  },
  {
    slug: "sisxldenis-simulaciuri-kursi",
    title: "Postpartum haemorrhage: simulation course",
    type: "Course",
    start: "2026-11-08",
    end: "2026-11-09",
    timeLabel: "09:30 – 17:00",
    location: "Simulation Centre, Tbilisi State Medical University",
    city: "Tbilisi",
    online: false,
    price: "160 GEL · 96 GEL for members",
    cme: "12 CME credits",
    seats: 24,
    registrationOpen: true,
    excerpt:
      "A two-day intensive course combining teamwork, protocols and technical skills drills.",
    image: IMG.eventSimulation,
    agenda: [
      { time: "Day 1 · 09:30", title: "Massive haemorrhage protocol" },
      { time: "Day 1 · 13:30", title: "Balloon tamponade and compression sutures" },
      { time: "Day 2 · 09:30", title: "Team scenarios on the simulator" },
      { time: "Day 2 · 14:00", title: "Debriefing and assessment" },
    ],
    speakers: ["Dr Levan Jorbenadze", "Dr Mariam Tsiklauri"],
    body: [
      "The course is built around high-fidelity simulation. Each participant works through at least four scenarios in different roles.",
      "Places are limited to 24. Teams from regional maternity units are given priority.",
    ],
  },
  {
    slug: "wliuri-saerto-kreba-2026",
    title: "Annual general assembly",
    type: "General assembly",
    start: "2026-12-07",
    timeLabel: "17:00 – 19:00",
    location: "Tbilisi Congress Centre, Hall B",
    city: "Tbilisi",
    online: false,
    price: "Members only",
    registrationOpen: true,
    excerpt:
      "Annual report, approval of the budget and discussion of working group priorities.",
    image: IMG.eventMeeting,
    speakers: ["Board"],
    body: [
      "The assembly takes place on the final day of the congress. Every active member with the current year's dues paid is entitled to attend and vote.",
      "The agenda is emailed to members 21 days before the meeting.",
    ],
  },
  {
    slug: "ultrabgera-me2-trimestri-kursi",
    title: "Second-trimester anomaly scanning — certification course",
    type: "Course",
    start: "2027-02-12",
    end: "2027-02-14",
    timeLabel: "10:00 – 16:00",
    location: "MFM Training Centre",
    city: "Tbilisi",
    online: false,
    price: "240 GEL · 140 GEL for members",
    cme: "16 CME credits",
    seats: 20,
    registrationOpen: false,
    excerpt:
      "A three-day course in standardised anomaly scanning technique and quality control, with an examination and certificate.",
    image: IMG.eventCourse,
    speakers: ["Dr Giorgi Maisuradze", "Dr Ana Kvaratskhelia"],
    body: [
      "Registration opens in December 2026. In the meantime you can join the waiting list.",
      "Participants sit a practical examination at the end of the course; those who pass receive an MFM Georgia certificate.",
    ],
  },
  {
    slug: "regionuli-shexvedra-qutaisi",
    title: "Regional meeting — Kutaisi",
    type: "Workshop",
    start: "2026-09-26",
    timeLabel: "11:00 – 16:00",
    location: "Kutaisi Referral Hospital",
    city: "Kutaisi",
    online: false,
    price: "Free",
    cme: "4 CME credits",
    seats: 60,
    registrationOpen: true,
    excerpt:
      "An implementation workshop on the pre-eclampsia guideline for healthcare facilities across the Imereti region.",
    image: IMG.eventRegional,
    speakers: ["Dr Ekaterine Lomidze", "Regional coordinators"],
    body: [
      "The meeting covers the practical side of putting the updated guideline into use: assessing resources, audit indicators and referral algorithms.",
      "Attendance is free, but places are limited so registration in advance is required.",
    ],
  },
  {
    slug: "tyupebis-martva-vebinari",
    title: "Management of multiple pregnancy",
    type: "Webinar",
    start: "2026-06-18",
    timeLabel: "19:00 – 20:00",
    location: "Online (Zoom)",
    city: "Online",
    online: true,
    price: "Free",
    cme: "1 CME credit",
    registrationOpen: false,
    excerpt:
      "Determining chorionicity, the monitoring schedule and early recognition of TTTS. A recording is available.",
    image: IMG.eventWebinar,
    speakers: ["Dr Ana Kvaratskhelia"],
    body: [
      "The webinar took place on 18 June 2026. The recording and presentation slides are available on the learning platform.",
    ],
  },
];
