import type { Guideline } from "../types";

export const guidelineTopics: string[] = [
  "Hypertension",
  "Diabetes",
  "Preterm birth",
  "Ultrasound",
  "Infections",
  "Multiple pregnancy",
  "Haemorrhage",
  "Genetics",
];

export const guidelineTypes: string[] = ["Guideline", "Protocol", "Consensus", "Checklist"];

export const guidelines: Guideline[] = [
  {
    slug: "preeklampsia-martva",
    code: "SG-001",
    title: "Pre-eclampsia: screening, prophylaxis and management",
    summary:
      "A complete document covering first-trimester risk assessment through to timing of delivery, including aspirin prophylaxis and the use of magnesium sulphate.",
    topic: "Hypertension",
    type: "Guideline",
    year: 2026,
    version: "3.0",
    pages: 48,
    updated: "2026-08-18",
    authors: "Hypertensive Disorders Working Group",
    keyPoints: [
      "Combined screening at 11–13+6 weeks to identify high risk",
      "Aspirin 150 mg at night, from week 12 to week 36",
      "Magnesium sulphate for eclampsia prophylaxis when severe features are present",
      "Delivery at 37 weeks without severe features; from 34 weeks in severe disease",
    ],
    body: [
      "Pre-eclampsia remains one of the leading causes of maternal morbidity and mortality. This document brings together recommendations on screening, prophylaxis, diagnosis and management.",
      "## Risk assessment",
      "Every pregnant patient should have a history-based risk assessment at the first visit. Aspirin prophylaxis is indicated where one major or two minor risk factors are present.",
      "## Monitoring",
      "Once diagnosed, blood pressure, laboratory markers and fetal wellbeing require regular assessment. The frequency of monitoring is determined by whether severe features are present.",
      "## Postpartum care",
      "Blood pressure control should continue for at least six weeks. Patients must be given information about the symptoms of late-onset pre-eclampsia.",
    ],
  },
  {
    slug: "gestaciuri-diabeti",
    code: "SG-002",
    title: "Gestational diabetes: screening and management",
    summary:
      "A single protocol based on the 75 g OGTT: diagnostic thresholds, dietary management, criteria for starting insulin and planning delivery.",
    topic: "Diabetes",
    type: "Protocol",
    year: 2026,
    version: "2.1",
    pages: 32,
    updated: "2026-04-25",
    authors: "Endocrinology Working Group",
    keyPoints: [
      "Universal screening with a 75 g OGTT at 24–28 weeks",
      "Diagnostic thresholds: 5.1 / 10.0 / 8.5 mmol/L",
      "First-line treatment is dietary and physical activity modification",
      "Insulin if targets are not reached within two weeks",
    ],
    body: [
      "The protocol takes account of the reality of local resources and sets the minimum mandatory standard for facilities at every level.",
      "## Self-monitoring",
      "After diagnosis, patients should be taught to use a glucometer. Four measurements a day are recommended: fasting and one hour after each main meal.",
      "## Planning delivery",
      "In diet-controlled gestational diabetes without complications, induction before 40+6 weeks is not mandatory.",
    ],
  },
  {
    slug: "naadrevi-mshobiaroba-prevencia",
    code: "SG-003",
    title: "Preterm birth: prevention and management",
    summary:
      "Indications for cervical length measurement, progesterone prophylaxis, cerclage criteria, tocolysis and corticosteroid prophylaxis.",
    topic: "Preterm birth",
    type: "Guideline",
    year: 2025,
    version: "2.4",
    pages: 41,
    updated: "2025-11-12",
    authors: "Perinatology Working Group",
    keyPoints: [
      "Cervical length measurement at 18–24 weeks with a history of preterm birth",
      "Vaginal progesterone when cervical length is ≤ 25 mm",
      "Corticosteroids at 24–34 weeks when preterm birth is anticipated",
      "Magnesium sulphate for neuroprotection below 32 weeks",
    ],
    body: [
      "The document covers primary and secondary prevention as well as intrapartum management.",
      "## Cerclage",
      "Indications fall into three categories: history-indicated, ultrasound-indicated and examination-indicated. Separate criteria are defined for each.",
      "## Transfer",
      "Where birth is anticipated between 22 and 32 weeks, transfer to a tertiary centre before delivery is recommended — in-utero transfer is preferable to neonatal transfer.",
    ],
  },
  {
    slug: "me2-trimestris-skriningi",
    code: "SG-004",
    title: "Second-trimester anomaly scanning standard",
    summary:
      "Twenty-two mandatory anatomical views, image quality criteria, documentation requirements and audit methodology.",
    topic: "Ultrasound",
    type: "Guideline",
    year: 2026,
    version: "1.3",
    pages: 36,
    updated: "2026-05-30",
    authors: "Ultrasound Diagnostics Committee",
    keyPoints: [
      "22 mandatory anatomical planes",
      "Optimal window for scanning: 18–22 weeks",
      "Images archived for at least 10 years",
      "Quarterly internal audit of 5% of studies",
    ],
    body: [
      "The standard is based on ISUOG international recommendations, adapted to locally available equipment and staffing.",
      "## When an abnormality is found",
      "Where a structural anomaly is suspected, the patient should be referred to a tertiary centre within seven days.",
    ],
  },
  {
    slug: "mshobiarobis-shemdgomi-sisxldena",
    code: "SG-005",
    title: "Management of postpartum haemorrhage",
    summary:
      "Prevention, early recognition, a stepwise management algorithm, the massive transfusion protocol and team communication.",
    topic: "Haemorrhage",
    type: "Protocol",
    year: 2025,
    version: "3.2",
    pages: 28,
    updated: "2025-09-04",
    authors: "Emergency Care Working Group",
    keyPoints: [
      "Active management of the third stage at every birth",
      "Quantitative (not visual) estimation of blood loss",
      "Tranexamic acid within three hours of diagnosis",
      "Activate the massive transfusion protocol above 1,500 mL",
    ],
    body: [
      "The protocol is built on a stepwise principle: each stage defines the action, the person responsible and the criterion for escalating.",
      "## Drills",
      "A massive haemorrhage scenario drill is recommended once a quarter, involving every on-call team.",
    ],
  },
  {
    slug: "mravalnayofiani-orsuloba",
    code: "SG-006",
    title: "Management of multiple pregnancy",
    summary:
      "Determining chorionicity, monitoring schedules by type, TTTS screening, and choosing the timing and mode of delivery.",
    topic: "Multiple pregnancy",
    type: "Guideline",
    year: 2025,
    version: "2.0",
    pages: 34,
    updated: "2025-07-20",
    authors: "Perinatology Working Group",
    keyPoints: [
      "Chorionicity must be determined before 14 weeks",
      "Monochorionic pregnancies monitored fortnightly from 16 weeks",
      "Dichorionic twins delivered at 37–38 weeks",
      "Monochorionic diamniotic twins at 36–37 weeks",
    ],
    body: [
      "Multiple pregnancy carries a substantially higher risk of complications, which is why intensive monitoring is required.",
      "## TTTS",
      "Screening for twin-to-twin transfusion syndrome is performed by assessing amniotic fluid volume and bladder visualisation at every visit.",
    ],
  },
  {
    slug: "infeqciebi-orsulobisas",
    code: "SG-007",
    title: "Infections in pregnancy: screening and management",
    summary:
      "Syphilis, hepatitis B, HIV, group B streptococcus, cytomegalovirus and toxoplasmosis — screening schedules and management algorithms.",
    topic: "Infections",
    type: "Guideline",
    year: 2025,
    version: "1.8",
    pages: 44,
    updated: "2025-05-16",
    authors: "Infectious Diseases Working Group",
    keyPoints: [
      "Universal screening for syphilis, HIV and hepatitis B at the first visit",
      "GBS screening at 36–37 weeks",
      "Indications for intrapartum antibiotic prophylaxis",
      "CMV — targeted rather than universal screening",
    ],
    body: [
      "The document consolidates recommendations for screening and managing infectious disease during pregnancy.",
      "## Antibiotic prophylaxis",
      "For GBS-positive patients, intrapartum prophylaxis should begin as early as possible after labour starts or membranes rupture.",
    ],
  },
  {
    slug: "prenataluri-genetikuri-skriningi",
    code: "SG-008",
    title: "Prenatal genetic screening and diagnosis",
    summary:
      "Indications for and limitations of NIPT, criteria for invasive diagnosis, principles of counselling and how results are communicated.",
    topic: "Genetics",
    type: "Consensus",
    year: 2026,
    version: "1.1",
    pages: 30,
    updated: "2026-01-28",
    authors: "Medical Genetics Working Group",
    keyPoints: [
      "NIPT is a screening, not a diagnostic, test",
      "A positive NIPT requires invasive confirmation",
      "Counselling before and after testing is mandatory",
      "The right to informed refusal is always protected",
    ],
    body: [
      "The document emphasises informed choice: screening should be offered, never imposed.",
      "## Communicating results",
      "An abnormal result must be delivered in person — not by telephone or letter — and accompanied by genetic counselling.",
    ],
  },
  {
    slug: "cerviqsis-ukmarisoba",
    code: "SG-009",
    title: "Cervical insufficiency",
    summary:
      "Diagnostic criteria, the three types of cerclage, the role of the pessary and subsequent monitoring.",
    topic: "Preterm birth",
    type: "Protocol",
    year: 2024,
    version: "1.5",
    pages: 22,
    updated: "2024-10-09",
    authors: "Perinatology Working Group",
    keyPoints: [
      "History-indicated cerclage at 12–14 weeks",
      "Ultrasound-indicated cerclage at ≤ 25 mm",
      "Cerclage removal at 36–37 weeks",
      "Pessary as an alternative in selected cases",
    ],
    body: [
      "The diagnosis of cervical insufficiency is clinical and rests on the history — painless cervical dilatation in the second trimester.",
    ],
  },
  {
    slug: "nayofis-zrdis-shezgudva",
    code: "SG-010",
    title: "Fetal growth restriction (FGR)",
    summary:
      "Definition by Delphi consensus, the Doppler monitoring algorithm and determining the timing of delivery.",
    topic: "Ultrasound",
    type: "Guideline",
    year: 2025,
    version: "2.2",
    pages: 38,
    updated: "2025-03-14",
    authors: "Ultrasound Diagnostics Committee",
    keyPoints: [
      "Separate algorithms for early (< 32 wk) and late (≥ 32 wk) FGR",
      "Umbilical artery Doppler as the basis of monitoring",
      "Ductus venosus determines timing of delivery in early FGR",
      "Cerebroplacental ratio in late FGR",
    ],
    body: [
      "Managing FGR requires regular assessment of fetal wellbeing and identifying the optimal moment for delivery — balancing prematurity against intrauterine risk.",
    ],
  },
  {
    slug: "mshobiarobis-induqcia",
    code: "SG-011",
    title: "Induction of labour protocol",
    summary:
      "Indications, methods of cervical ripening, oxytocin regimens and monitoring requirements.",
    topic: "Haemorrhage",
    type: "Protocol",
    year: 2024,
    version: "2.6",
    pages: 26,
    updated: "2024-12-02",
    authors: "Intrapartum Care Working Group",
    keyPoints: [
      "Bishop score to select the method of induction",
      "Misoprostol or dinoprostone for an unfavourable cervix",
      "Continuous cardiotocographic monitoring during oxytocin infusion",
      "Recognition and management of hyperstimulation",
    ],
    body: [
      "The protocol defines the minimum safety conditions for induction, including the ability to perform a caesarean section within 30 minutes.",
    ],
  },
  {
    slug: "meows-sakontrolo-purceli",
    code: "SC-001",
    title: "MEOWS — modified early obstetric warning system",
    summary:
      "A one-page chart for recording vital signs with automatic identification of warning thresholds.",
    topic: "Haemorrhage",
    type: "Checklist",
    year: 2026,
    version: "1.0",
    pages: 2,
    updated: "2026-07-01",
    authors: "Patient Safety Committee",
    keyPoints: [
      "Colour-coded thresholds — yellow and red zones",
      "One yellow or two red triggers → notify the physician immediately",
      "Recording frequency set by risk",
      "Print-ready A4 format",
    ],
    body: [
      "Implementing MEOWS is associated with earlier recognition of maternal deterioration. The chart is designed to work without an electronic system.",
    ],
  },
  {
    slug: "cesarean-sakontrolo-purceli",
    code: "SC-002",
    title: "Caesarean section safety checklist",
    summary:
      "The steps to complete before, during and after the operation, for verification by the whole team.",
    topic: "Haemorrhage",
    type: "Checklist",
    year: 2025,
    version: "1.2",
    pages: 2,
    updated: "2025-08-22",
    authors: "Patient Safety Committee",
    keyPoints: [
      "Three stages: sign in, time out, sign out",
      "Antibiotic prophylaxis within 60 minutes before skin incision",
      "Thromboprophylaxis risk assessment",
      "Quantitative recording of blood loss",
    ],
    body: [
      "The checklist is adapted from the WHO surgical safety checklist, with obstetric specifics added.",
    ],
  },
  {
    slug: "trombopropilaqtika",
    code: "SG-012",
    title: "Thromboprophylaxis in pregnancy and the postpartum period",
    summary:
      "The risk assessment scheme, weight-based dosing of low molecular weight heparin and determining duration.",
    topic: "Hypertension",
    type: "Guideline",
    year: 2024,
    version: "1.9",
    pages: 24,
    updated: "2024-06-11",
    authors: "Hypertensive Disorders Working Group",
    keyPoints: [
      "Risk assessment at the first visit, on admission and after delivery",
      "LMWH dose according to body weight",
      "Postpartum prophylaxis for 10 days to 6 weeks",
      "Timing intervals around regional anaesthesia",
    ],
    body: [
      "Venous thromboembolism remains an avoidable cause of maternal death. Systematic risk assessment reduces the number of missed cases.",
    ],
  },
];
