import type { NewsItem } from "../types";
import { IMG } from "../images";

export const newsCategories: string[] = [
  "Guideline",
  "Research",
  "Organisation",
  "Education",
  "Advocacy",
];

export const news: NewsItem[] = [
  {
    slug: "preeklampsiis-gaidlaini-2025",
    title: "Updated pre-eclampsia management guideline published",
    excerpt:
      "The document brings together revised recommendations on first-trimester screening, aspirin prophylaxis and the optimal timing of delivery.",
    category: "Guideline",
    date: "2026-08-18",
    author: "Hypertensive Disorders Working Group",
    readMinutes: 6,
    image: IMG.newsGuideline,
    featured: true,
    tags: ["pre-eclampsia", "screening", "hypertension"],
    body: [
      "The MFM Georgia hypertensive disorders working group has completed its revision of the national pre-eclampsia management guideline. The updated version draws on systematic reviews published between 2023 and 2025 together with the results of a local practice audit.",
      "## What has changed",
      "The main change concerns combined first-trimester screening. The document recommends assessing maternal history, mean arterial pressure, uterine artery pulsatility index and PlGF together at 11–13+6 weeks — wherever the test is available.",
      "For the high-risk group the aspirin dose is now set at 150 mg taken in the evening, started before week 12 and continued to week 36. The previous 75–100 mg range is retained only where a higher dose is contraindicated.",
      "## Timing of delivery",
      "In pre-eclampsia without severe features, delivery is recommended at 37 weeks. Where severe features are present, delivery from 34 weeks is advised once the mother is stabilised and corticosteroid prophylaxis has been given.",
      "> A guideline does not replace clinical judgement in an individual case — it defines the expected standard, and any departure from it should be documented and justified.",
      "## Implementation",
      "The document is freely available in Georgian and English. A series of regional workshops begins in September across nine centres, covering practical implementation questions and audit indicators.",
    ],
  },
  {
    slug: "regionuli-perinataluri-qseli",
    title: "Regional perinatal network adds two new centres",
    excerpt:
      "A 24/7 telephone consultation line for high-risk pregnancy cases is now operating in Kutaisi and Batumi.",
    category: "Organisation",
    date: "2026-08-04",
    author: "MFM Georgia office",
    readMinutes: 4,
    image: IMG.newsNetwork,
    featured: true,
    tags: ["regions", "network", "consultation"],
    body: [
      "The regional perinatal network launched in 2024 with the aim of providing timely, qualified consultation in high-risk pregnancy cases everywhere in Georgia.",
      "With the new centres the network now covers nine regional hubs. Each employs at least two certified perinatologists and has level 2 ultrasound diagnostics available.",
      "## How it works",
      "A physician at a district maternity unit can call a single number and be connected to the perinatologist on duty within 15 minutes. Where necessary, patient transfer is coordinated at the same time.",
      "In the first year, of the 1,040 calls received, 38% avoided an unnecessary transfer while 21% accelerated transfer to a tertiary centre.",
    ],
  },
  {
    slug: "naadrevi-mshobiaroba-kvleva",
    title: "National study on preterm birth prediction begins",
    excerpt:
      "A multicentre prospective study will assess the combined predictive value of cervical length and biomarkers in the Georgian population.",
    category: "Research",
    date: "2026-07-22",
    author: "Prof. Tamar Beridze",
    readMinutes: 5,
    image: IMG.newsResearch,
    tags: ["preterm birth", "research", "cervix"],
    body: [
      "The study will enrol 2,400 singleton pregnancies across six centres. Participants will undergo transvaginal cervical length measurement and fetal fibronectin testing at 18–24 weeks.",
      "## Why it matters",
      "Over the past decade the rate of preterm birth in Georgia has fluctuated between 7% and 9%. International predictive models have not been validated in the local population, which limits their practical use.",
      "The results will underpin a national preterm birth prevention protocol, planned for publication in 2027.",
      "## Taking part",
      "Centres wishing to join the study can apply until 30 October 2026.",
    ],
  },
  {
    slug: "cme-programa-2026",
    title: "2026 continuing education programme published",
    excerpt:
      "Fourteen courses are scheduled for the year, six of them simulation training in the management of obstetric emergencies.",
    category: "Education",
    date: "2026-07-09",
    author: "Education Committee",
    readMinutes: 3,
    image: IMG.newsEducation,
    tags: ["CME", "training", "simulation"],
    body: [
      "The programme includes both online modules and practical courses delivered in person. Every activity is accredited and participants receive CME credits.",
      "## Priority topics",
      "This year's focus is postpartum haemorrhage management, intrapartum fetal assessment, multiple pregnancy and maternal critical care.",
      "MFM members receive a 40% discount, while residents have free access to the online modules.",
    ],
  },
  {
    slug: "dedis-sikvdilianobis-audit",
    title: "Confidential enquiry into maternal deaths: annual report",
    excerpt:
      "Analysis of 2025 data found that 54% of cases were potentially avoidable — most often because deterioration was recognised too late.",
    category: "Advocacy",
    date: "2026-06-27",
    author: "Audit Working Group",
    readMinutes: 7,
    image: IMG.newsAdvocacy,
    tags: ["maternal mortality", "audit", "quality"],
    body: [
      "The confidential enquiry is run in cooperation with the Ministry of Health. Its purpose is to identify systemic gaps — not to assign individual blame.",
      "## Key findings",
      "The most frequent failing was delayed recognition of critical illness, particularly in sepsis and massive haemorrhage. Early warning systems (MEOWS) were in place in only 41% of facilities.",
      "The second recurring problem was delayed transfer: in a third of cases, moving the patient to an appropriate level of care took more than four hours.",
      "## Recommendations",
      "The report makes three principal recommendations: mandatory MEOWS implementation in every maternity unit, quarterly massive haemorrhage drills, and a single transfer coordination centre.",
    ],
  },
  {
    slug: "akhali-gamgeoba-2026",
    title: "New board takes office",
    excerpt:
      "The general assembly approved the 2026–2028 board; Prof. Nino Chkhartishvili was re-elected president.",
    category: "Organisation",
    date: "2026-06-12",
    author: "MFM Georgia office",
    readMinutes: 3,
    image: IMG.newsBoard,
    tags: ["board", "elections"],
    body: [
      "The general assembly was held in Tbilisi on 8 June; a quorum was reached with 312 members present and all nine board positions were filled.",
      "The new board named its priorities as expanding the regional network, auditing guideline implementation, and accrediting the fellowship programme.",
    ],
  },
  {
    slug: "ultrabgeriti-skriningis-standarti",
    title: "Quality standard for second-trimester anomaly scanning",
    excerpt:
      "The document sets out the mandatory anatomical views and the criteria for assessing image quality.",
    category: "Guideline",
    date: "2026-05-30",
    author: "Ultrasound Diagnostics Committee",
    readMinutes: 5,
    image: IMG.newsUltrasound,
    tags: ["ultrasound", "screening", "quality"],
    body: [
      "The standard is based on ISUOG recommendations, adapted to locally available resources.",
      "## Mandatory views",
      "The document specifies 22 mandatory anatomical planes, among them three levels of the fetal brain, the facial profile, the four-chamber view and outflow tracts, the abdominal wall, the kidneys and three projections of the spine.",
      "## Audit",
      "Units are advised to re-review a random 5% of screening studies each quarter using a standardised assessment sheet.",
    ],
  },
  {
    slug: "kongresi-2026-registracia",
    title: "Registration for the Global Congress is open",
    excerpt:
      "5–7 December, Tbilisi. Early-bird rates apply until 1 October; abstract submission closes 15 September.",
    category: "Education",
    date: "2026-05-14",
    author: "Organising Committee",
    readMinutes: 3,
    image: IMG.newsCongress,
    tags: ["congress", "registration", "abstracts"],
    body: [
      "The congress brings together more than 40 speakers from Georgia, Europe and the United States. Five plenary sessions and 12 parallel workshops are planned across three days.",
      "## Abstracts",
      "Original research, case series and quality improvement projects are all welcome. The three best submissions will be presented in a plenary session.",
      "Reduced rates apply for students and residents, and 30 travel grants are available.",
    ],
  },
  {
    slug: "gestaciuri-diabetis-protokoli",
    title: "A single protocol for gestational diabetes screening",
    excerpt:
      "A 75 g OGTT at 24–28 weeks is recommended for all pregnancies; in the high-risk group, additionally at the first visit.",
    category: "Guideline",
    date: "2026-04-25",
    author: "Endocrinology Working Group",
    readMinutes: 4,
    image: IMG.newsDiabetes,
    tags: ["diabetes", "screening", "protocol"],
    body: [
      "The protocol brings screening, diagnosis, dietary management and pharmacological treatment together in a single document.",
      "## Diagnostic thresholds",
      "Gestational diabetes is diagnosed when one or more values on a 75 g OGTT are exceeded: 5.1 mmol/L fasting, 10.0 mmol/L at one hour, 8.5 mmol/L at two hours.",
      "First-line treatment is dietary and physical activity modification; insulin is started if targets are not met within two weeks.",
    ],
  },
  {
    slug: "telemedicinis-piloti",
    title: "Telehealth pilot completed in three regions",
    excerpt:
      "The six-month pilot delivered 640 remote consultations, with 92% patient satisfaction.",
    category: "Organisation",
    date: "2026-04-03",
    author: "Digital Health Group",
    readMinutes: 4,
    image: IMG.newsTelehealth,
    tags: ["telehealth", "pilot", "regions"],
    body: [
      "The pilot ran in Kakheti, Samtskhe-Javakheti and Racha-Lechkhumi — the regions where access to a perinatologist is most limited.",
      "Consultations used a hybrid format: the local physician joined the session together with the patient, which made it possible to review ultrasound images in real time.",
      "## Results",
      "Average waiting time for a consultation fell from 21 days to four. Travel-related costs for patients dropped by an average of 180 GEL.",
    ],
  },
  {
    slug: "kvlevis-grantebi-2026",
    title: "Young investigator grant competition announced",
    excerpt:
      "Five grants of 12,000 GEL each, for first research projects by residents and fellows.",
    category: "Research",
    date: "2026-03-19",
    author: "Scientific Committee",
    readMinutes: 3,
    image: IMG.newsGrant,
    tags: ["grant", "research", "residents"],
    body: [
      "Obstetrics and gynaecology residents and maternal-fetal medicine fellows with an independent research idea and institutional support are eligible to apply.",
      "Applications must include a short protocol summary (maximum five pages), a budget and a letter of support from a mentor. The deadline is 30 November.",
    ],
  },
  {
    slug: "pacientis-broshurebi",
    title: "Five new information leaflets for patients",
    excerpt:
      "Plain-language materials on high-risk pregnancy, twins, cervical insufficiency and other topics.",
    category: "Advocacy",
    date: "2026-02-27",
    author: "Communications Group",
    readMinutes: 2,
    image: IMG.newsBrochure,
    tags: ["patients", "leaflets", "communication"],
    body: [
      "The leaflets were developed together with patient focus groups, so that the text is understandable without a medical background.",
      "All materials are free to download as PDFs and are distributed in print through partner clinics.",
    ],
  },
];
