import type { Specialist } from "../types";

export const cities: string[] = [
  "Tbilisi",
  "Kutaisi",
  "Batumi",
  "Rustavi",
  "Zugdidi",
  "Telavi",
  "Gori",
  "Akhaltsikhe",
];

export const subspecialties: string[] = [
  "Perinatology",
  "Ultrasound diagnostics",
  "Medical genetics",
  "Neonatology",
  "Obstetric anaesthesia",
];

export const languages: string[] = ["Georgian", "English", "Russian", "Armenian", "Azerbaijani"];

export const specialists: Specialist[] = [
  {
    id: "sp-01",
    name: "Prof. Nino Chkhartishvili",
    title: "Perinatologist, Medical Director",
    clinic: "National Centre for Maternal and Child Health",
    city: "Tbilisi",
    region: "Tbilisi",
    subspecialties: ["Perinatology", "Ultrasound diagnostics"],
    languages: ["Georgian", "English", "Russian"],
    phone: "+995 32 291 44 10",
    email: "n.chkhartishvili@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2004,
    bio: "Specialises in pre-eclampsia and hypertensive disorders. President of MFM Georgia.",
  },
  {
    id: "sp-02",
    name: "Prof. Tamar Beridze",
    title: "Perinatologist, Head of Research",
    clinic: "Tbilisi State Medical University Clinic",
    city: "Tbilisi",
    region: "Tbilisi",
    subspecialties: ["Perinatology"],
    languages: ["Georgian", "English"],
    phone: "+995 32 254 08 77",
    email: "t.beridze@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2007,
    bio: "Principal investigator of the national study on preterm birth prevention.",
  },
  {
    id: "sp-03",
    name: "Dr Giorgi Maisuradze",
    title: "Ultrasound diagnostics specialist",
    clinic: "Prenatal Diagnostics Centre",
    city: "Tbilisi",
    region: "Tbilisi",
    subspecialties: ["Ultrasound diagnostics", "Medical genetics"],
    languages: ["Georgian", "English", "Russian"],
    phone: "+995 32 220 31 55",
    email: "g.maisuradze@example.ge",
    acceptsReferrals: true,
    telehealth: false,
    since: 2011,
    bio: "Specialist in fetal echocardiography and the diagnosis of structural anomalies.",
  },
  {
    id: "sp-04",
    name: "Dr Ekaterine Lomidze",
    title: "Perinatologist",
    clinic: "Kutaisi Referral Hospital",
    city: "Kutaisi",
    region: "Imereti",
    subspecialties: ["Perinatology"],
    languages: ["Georgian", "English"],
    phone: "+995 431 24 55 09",
    email: "e.lomidze@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2013,
    bio: "Coordinator of the regional perinatal network in Imereti.",
  },
  {
    id: "sp-05",
    name: "Dr Levan Jorbenadze",
    title: "Obstetrician-gynaecologist, emergency care",
    clinic: "Batumi Medical Centre",
    city: "Batumi",
    region: "Adjara",
    subspecialties: ["Perinatology", "Obstetric anaesthesia"],
    languages: ["Georgian", "English", "Russian"],
    phone: "+995 422 27 61 30",
    email: "l.jorbenadze@example.ge",
    acceptsReferrals: true,
    telehealth: false,
    since: 2009,
    bio: "Instructor in the management of massive haemorrhage and maternal critical care.",
  },
  {
    id: "sp-06",
    name: "Dr Ana Kvaratskhelia",
    title: "Ultrasound diagnostics specialist",
    clinic: "National Centre for Maternal and Child Health",
    city: "Tbilisi",
    region: "Tbilisi",
    subspecialties: ["Ultrasound diagnostics"],
    languages: ["Georgian", "English"],
    phone: "+995 32 291 44 22",
    email: "a.kvaratskhelia@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2015,
    bio: "Specialist in multiple pregnancy and the diagnosis of TTTS.",
  },
  {
    id: "sp-07",
    name: "Dr Mariam Tsiklauri",
    title: "Obstetric anaesthetist",
    clinic: "Tbilisi State Medical University Clinic",
    city: "Tbilisi",
    region: "Tbilisi",
    subspecialties: ["Obstetric anaesthesia"],
    languages: ["Georgian", "English"],
    phone: "+995 32 254 08 91",
    email: "m.tsiklauri@example.ge",
    acceptsReferrals: false,
    telehealth: false,
    since: 2012,
    bio: "Specialist in obstetric anaesthesia safety and massive transfusion protocols.",
  },
  {
    id: "sp-08",
    name: "Dr Davit Ghlonti",
    title: "Neonatologist",
    clinic: "Zugdidi Regional Hospital",
    city: "Zugdidi",
    region: "Samegrelo",
    subspecialties: ["Neonatology"],
    languages: ["Georgian", "Russian"],
    phone: "+995 415 22 40 18",
    email: "d.ghlonti@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2010,
    bio: "Specialist in intensive care for preterm newborns.",
  },
  {
    id: "sp-09",
    name: "Dr Sopio Gelashvili",
    title: "Medical geneticist",
    clinic: "Genetic Counselling Centre",
    city: "Tbilisi",
    region: "Tbilisi",
    subspecialties: ["Medical genetics"],
    languages: ["Georgian", "English", "Russian"],
    phone: "+995 32 238 77 04",
    email: "s.gelashvili@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2014,
    bio: "Specialist in prenatal genetic counselling and NIPT interpretation.",
  },
  {
    id: "sp-10",
    name: "Dr Zurab Kiknadze",
    title: "Obstetrician-gynaecologist",
    clinic: "Rustavi Central Hospital",
    city: "Rustavi",
    region: "Kvemo Kartli",
    subspecialties: ["Perinatology"],
    languages: ["Georgian", "Azerbaijani", "Russian"],
    phone: "+995 341 25 33 60",
    email: "z.kiknadze@example.ge",
    acceptsReferrals: true,
    telehealth: false,
    since: 2016,
    bio: "Member of the Kvemo Kartli regional network; works with multilingual patients.",
  },
  {
    id: "sp-11",
    name: "Dr Natia Bolkvadze",
    title: "Perinatologist",
    clinic: "Batumi Medical Centre",
    city: "Batumi",
    region: "Adjara",
    subspecialties: ["Perinatology", "Ultrasound diagnostics"],
    languages: ["Georgian", "English", "Turkish"],
    phone: "+995 422 27 61 44",
    email: "n.bolkvadze@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2017,
    bio: "Coordinator of the regional perinatal network in Adjara.",
  },
  {
    id: "sp-12",
    name: "Dr Irakli Khutsishvili",
    title: "Obstetrician-gynaecologist",
    clinic: "Telavi District Hospital",
    city: "Telavi",
    region: "Kakheti",
    subspecialties: ["Perinatology"],
    languages: ["Georgian", "Russian"],
    phone: "+995 350 27 18 22",
    email: "i.khutsishvili@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2018,
    bio: "Participant in the telehealth pilot; regional coordinator for Kakheti.",
  },
  {
    id: "sp-13",
    name: "Dr Ketevan Shengelia",
    title: "Neonatologist",
    clinic: "National Centre for Maternal and Child Health",
    city: "Tbilisi",
    region: "Tbilisi",
    subspecialties: ["Neonatology"],
    languages: ["Georgian", "English"],
    phone: "+995 32 291 44 38",
    email: "k.shengelia@example.ge",
    acceptsReferrals: true,
    telehealth: false,
    since: 2011,
    bio: "Author of the neonatal transfer and stabilisation protocols.",
  },
  {
    id: "sp-14",
    name: "Dr Gvantsa Tabatadze",
    title: "Obstetrician-gynaecologist",
    clinic: "Gori Referral Centre",
    city: "Gori",
    region: "Shida Kartli",
    subspecialties: ["Perinatology"],
    languages: ["Georgian", "English"],
    phone: "+995 370 27 09 15",
    email: "g.tabatadze@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2019,
    bio: "Member of the Shida Kartli regional network; trainer in gestational diabetes management.",
  },
  {
    id: "sp-15",
    name: "Dr Aleksandre Melikishvili",
    title: "Perinatologist",
    clinic: "Akhaltsikhe Regional Hospital",
    city: "Akhaltsikhe",
    region: "Samtskhe-Javakheti",
    subspecialties: ["Perinatology", "Ultrasound diagnostics"],
    languages: ["Georgian", "Armenian", "Russian"],
    phone: "+995 365 22 14 07",
    email: "a.melikishvili@example.ge",
    acceptsReferrals: true,
    telehealth: true,
    since: 2015,
    bio: "Coordinator of the Samtskhe-Javakheti regional network; works with Armenian-speaking patients.",
  },
];
